routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::resource('/work', App\Http\Controllers\WorkController::class);
Route::get('/import', [App\Http\Controllers\WorkController::class, 'import'])->name('import');
Route::post('/upload', [App\Http\Controllers\WorkController::class, 'upload'])->name('upload');
Route::get('/currency', [App\Http\Controllers\CurrencyController::class, 'index'])->name('currency');
Route::post('/transfer', [App\Http\Controllers\CurrencyController::class, 'transfer'])->name('transfer');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Work.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Work extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function users()
    {
    	return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function statuses()
    {
    	return $this->belongsTo(Status::class, 'status', 'id');
    }
}

app/Http/Controllers/WorkController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Work;
use App\Models\User;
use App\Models\Status;
use App\Imports\WorkImport;

class WorkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('works.index', [
            'works' => Work::with('users')->paginate(10),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('works.create', [
                'work' => [],
                'users' => User::all(),
                'statuses' => Status::all()
            ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $messages = [
                'required' => 'Все поля должны быть заполнены',
                'max' => 'Максимальная длина поля 191 символ'
            ];

            $validator = $this->validate($request, [
                'task' => 'required|string|max:191',
                'user_id' => 'required',
                'deadline' => 'required|date',
                'status' => 'required'
            ], $messages);

        $work = Work::create($request->all());

        request()->session()->flash('success', 'Задача успешно создана');
        return redirect()->route('work.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Work $work)
    {
        return view('works.edit', [
                'work' => $work,
                'users' => User::all(),
                'statuses' => Status::all()
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Work $work)
    {
        $messages = [
                'required' => 'Все поля должны быть заполнены',
                'max' => 'Максимальная длина поля 191 символ'
            ];

            $validator = $this->validate($request, [
                'task' => 'required|string|max:191',
                'user_id' => 'required',
                'deadline' => 'required|date',
                'status' => 'required'
            ], $messages);

        $work->task = $request['task'];
        $work->user_id = $request['user_id'];
        $work->deadline = $request['deadline'];
        $work->status = $request['status'];
        $work->save();

        request()->session()->flash('success', 'Задача успешно обновлена');
        return redirect()->route('work.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Work $work)
    {
        $work->delete();
        request()->session()->flash('success', 'Задача успешно удалена');
        return redirect()->route('work.index');
    }

    public function import()
    {
        return view('works.import');
    }

    public function upload(Request $request)
    {
        $validator = $this->validate($request, [
            'file' => 'required|max:100000|mimes:xlsx,xls,csv'
        ]);

        if($validator){
            \Excel::import(new WorkImport, request()->file('file'));
            return redirect()->back()->with(['success' => 'Файл успешно импортирован']);
        }else{
            return redirect()->back()->with(['errors' => $validator->errors()->all()]);
        }
    }
}

resources/views/works/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
	<hr/>
	<form action="{{ route('work.store') }}" method="post" class="form-horizontal">
		{{ csrf_field() }}
		@include('works.partials.form')
	</form>
</div>

@endsection

resources/views/works/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
	<hr/>
	<form action="{{ route('work.update', $work) }}" method="post" class="form-horizontal">
		<input type="hidden" name="_method" value="PUT"> 
		{{ csrf_field() }}
		@include('works.partials.form')
	</form>
</div>

@endsection

resources/views/works/import.blade.php
@extends('layouts.app')

@section('content')
   <div class="container">
      @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @if (Session::has('success'))
        <div class="alert alert-success">{{ Session::get('success') }}</div>
    @endif
         @if(isset($error_nofile))
         <div class="row" style="color: red; font-size: 18px;">Укажите, пожалуйста, файл для загрузки</div>
         @endif
   	   <div class="row">
   	   	<form action="{{ route('upload') }}" method="post" enctype="multipart/form-data" id="import" class="form-horizontal">
                     {{ csrf_field() }}
                     <table class="form">
                        <tr>
                           <td>
                              Импорт из XLS, XLSX или CSV файла
                           </td>
                        </tr>
                        <tr>
                           <td>Загружаемый файл<br /><br /><input type="file" name="file" id="upload" /></td>
                        </tr>
                        <tr>
                           <td class="buttons"><a onclick="uploadData();" class="btn btn-primary"><span>Импорт</span></a></td>
                        </tr>
                     </table>
                  </form>
   	   </div>
   </div>
   <script>
      function uploadData() {
        $('#import').submit();
      }
   </script>
@endsection

resources/views/works/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <hr/>
  @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @if (Session::has('success'))
        <div class="alert alert-success">{{ Session::get('success') }}</div>
    @endif
  <a href="/work/create" class="btn btn-primary pull-right"><i class="fa fa-plus-square-o"> Создать</i></a>
  <a href="{{ route('import') }}" class="btn btn-primary pull-right"><i class="fa fa-plus-square-o"> Импорт</i></a>
  <table class="table table-striped">
    <thead>
      <th>Задача</th>
      <th>Ответственный</th>
      <th class="text-right">Действия</th>
    </thead>
    <tbody>
      @forelse($works as $work)
      <tr>
        <td>{{ $work->task }}</td>
        <td>{{ $work->users->name }}</td>
        <td class="text-right">
            <form action="{{ route('work.destroy', $work) }}" onsubmit="if(confirm('Delete?')){return true}else{return false}" method="post">
                  <input type="hidden" name="_method" value="DELETE"> 
                  {{ csrf_field() }}
                  <a href="{{ route('work.edit', $work) }}" class="btn btn-default"><i class="fa fa-edit"></i></a>
                  <button type="submit" class="btn"><i class="fa fa-trash"></i></button>
                </form></td>
      </tr>
      @empty
      <tr>
        <td colspan="3" class="text-center">Нет задач</td>
      </tr>
      @endforelse
    </tbody>
    <tfoot>
      <tr>
        <td colspan="3">
          <ul class="pagination full-right">
            {{ $works->links() }}
          </ul>
        </td>
      </tr>
    </tfoot>
  </table>
</div>

@endsection